spring.application.name=TelIngestionService

# 1. Circuit Breaker Settings
resilience4j.circuitbreaker.instances.telemetryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.telemetryService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.telemetryService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.telemetryService.slidingWindowSize=10

# 2. TimeLimiter Settings
resilience4j.timelimiter.instances.telemetryService.timeoutDuration=2s
resilience4j.timelimiter.instances.telemetryService.cancelRunningFuture=true

# 3. Retry Settings
resilience4j.retry.instances.telemetryService.maxAttempts=3
resilience4j.retry.instances.telemetryService.waitDuration=500ms
resilience4j.retry.instances.telemetryService.retryExceptions[0]=org.springframework.kafka.KafkaException
resilience4j.retry.instances.telemetryService.retryExceptions[1]=java.io.IOException


spring.ai.mcp.server.name=tel-ingestion-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.protocol=SSE
